### ISSUE TITLE
How to handle messages?

### ISSUE THREAD

**Issue by afshar-mohammad** [rubenlagus/Deepthougth#14]
Well, I think a brief documentation on how to handle messages in your custom update handler is essential here. As I saw, we have `onTLUpdateShortMessageCustom()`, `onTLUpdateNewMessageCustom()` and `onTLAbsMessageCustom()` overriden in the echo plugin for message handling, but I can't figure out the differences between them. I have no idea what kind of messages invoke which one of the above functions.

Assuming that I want to handle all new messages coming (i.e. from private chat, secret chat, group, channel and bot), can you briefly explain what are the functions I have to override?

thanks

**Comment by afshar-mohammad** [comment]
and one more thing! why do all these methods have `protected` access modifier? I actually want to have all my code in my very own package (not org.telegram.*), but this `protected` makes me unable to override the methods. :pensive:

**Comment by rubenlagus** [comment]
`onTLUpdateShortMessageCustom` will handle https://core.telegram.org/constructor/updateShortMessage

`onTLUpdateNewMessageCustom` will handle https://core.telegram.org/constructor/updateNewMessage

`onTLUpdateShortChatMessageCustom`will handle https://core.telegram.org/constructor/updateShortChatMessage

`onTLAbsMessageCustom` will handle https://core.telegram.org/type/Message

For channels, you need to use those that have "Channel" in the name.

**Comment by rubenlagus** [comment]
And you can override a method that has protected modifier from a subclass even if it is not in the same package: http://docs.oracle.com/javase/specs/jls/se8/html/jls-6.html#jls-6.6.2

**Comment by afshar-mohammad** [comment]
oh yeah! that was my IDE bug, underlining those Overrides in red. IDE restart fixed it! 😁 

thanks for the telegram api links.
