### ISSUE TITLE
get error while using TLRequestMessageHistoery

### ISSUE THREAD

**Issue by mehdi1602** [rubenlagus/Deepthougth#19]
I used as below

                TLRequestMessagesGetHistory tlReq = new TLRequestMessagesGetHistory();
                TLAbsInputPeer _peer = (TLAbsInputPeer) new TLInputPeerChat();
                ((TLInputPeerChat) _peer).setChatId(update.getChannelId()); 
                tlReq.setPeer(_peer);
                TLAbsMessages messagesEx = kernelComm.getApi().doRpcCall(tlReq);`
but all the time i get exceptions INVALID_CHANNEL_ID or INVALID_CHAT_ID

          ` org.telegram.api.engine.RpcException: CHAT_ID_INVALID`
could you please help me to know why I get this error?

**Comment by amin1softco** [comment]
this code i think solve your problem consider super group is channel too.
````java
TLAbsInputPeer fpeer = new TLInputPeerChannel();
         ((TLInputPeerChannel)fpeer).setAccessHash(chan.getAccessHash());
         ((TLInputPeerChannel)fpeer).setChannelId(chan.getId());

 TLRequestMessagesGetHistory req = new TLRequestMessagesGetHistory();
   req.setPeer(fpeer);
   req.setAddOffset(0);
   req.setLimit(10);
   req.setMaxId(0);
   req.setMinId(0);
   req.setOffsetDate(0);
   req.setOffsetId(0);
   
      TLAbsMessages dialogs = (TLAbsMessages)kernelComm.getApi().doRpcCall (req);
          TLVector messages = dialogs.getMessages();
          for (Object msg : messages ){
if (msg  instanceof TLMessage){
//your code
}
}
````

**Comment by edbrik** [comment]
how get channels id and hash?

**Comment by afshar-mohammad** [comment]
@edbrik check this:
https://github.com/rubenlagus/TelegramApi/issues/7

**Comment by rubenlagus** [comment]
@edbrik You should get them in the https://github.com/rubenlagus/Deepthought/blob/master/Deepthought/src/main/java/org/telegram/plugins/echo/handlers/ChatsHandler.java while getting updates. You can also resolve them from username or from join links.

**Comment by mehdi1602** [comment]
how to join to a super group by join link?

**Comment by afshar-mohammad** [comment]
@mehdi1602 assuming `str` is the join link:

                    String hash = str.split("/")[(str.split("/").length)-1];
                    TLRequestMessagesImportChatInvite in = new TLRequestMessagesImportChatInvite();
                    in.setHash(hash);
                    try {
                        TLAbsUpdates bb = kernelComm.getApi().doRpcCall(in);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

**Comment by mehdi1602** [comment]
thank you @pazis . could you please let me know how can I get Info of a Channel or a Supergroup?
