### ISSUE TITLE
Get Channel Info

### ISSUE THREAD

**Issue by mehdi1602** [rubenlagus/Deepthougth#22]
Hi guys,
do you know how can I get Info section of a Channel?

**Comment by rubenlagus** [comment]
You will receive it in your implementation of [IChatsHandler](https://github.com/rubenlagus/TelegramApi/blob/51713e9b6eb9e0ae0d4bbbe3d4deffff9b7f01e4/src/main/java/org/telegram/bot/handlers/interfaces/IChatsHandler.java)

**Comment by mehdi1602** [comment]
unfortunatley non of the Chat subclasses has no method name getInfo() or s'th like this method.
the info section of a Channel or Super group is so important but i don't know how to get this information

**Comment by amin1softco** [comment]
````java
TLRequestChannelsGetFullChannel req = new TLRequestChannelsGetFullChannel();
            TLInputChannel peer = new TLInputChannel();
            peer.setAccessHash(channel.getAccessHash());
            peer.setChannelId(channel.getId());
           req.setChannel(peer);
           TLMessagesChatFull res =  kernel.getKernelComm().getApi().doRpcCall(req);
           if (res.getFullChat() instanceof TLChannelFull)
            TLChannelFull info= (TLChannelFull) res.getFullChat();
//yourcode...
````
😄 happynewyear

**Comment by mehdi1602** [comment]
awsome amin
